# TCL File Generated by Component Editor 22.1
# Wed Jul 26 20:14:28 MSK 2023
# DO NOT MODIFY


# 
# UART "UART" v2.4
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module UART
# 
set_module_property DESCRIPTION ""
set_module_property NAME UART
set_module_property VERSION 2.4
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols"
set_module_property AUTHOR "RB"
set_module_property DISPLAY_NAME UART
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL uart_mm_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_to_reg.sv   SYSTEM_VERILOG  PATH RTL/avalon_to_reg.sv
add_fileset_file baud_gen.v         VERILOG         PATH RTL/baud_gen.v
add_fileset_file sc_fifo.sv         SYSTEM_VERILOG  PATH RTL/sc_fifo.sv
add_fileset_file uart_mm_top.sv     SYSTEM_VERILOG  PATH RTL/uart_mm_top.sv TOP_LEVEL_FILE
add_fileset_file uart_rx.v          VERILOG         PATH RTL/uart_rx.v
add_fileset_file uart_rx_tx.sv      SYSTEM_VERILOG  PATH RTL/uart_rx_tx.sv
add_fileset_file uart_tx.v          VERILOG         PATH RTL/uart_tx.v


# 
# parameters
# 
add_parameter fifo_depth INTEGER 10
set_parameter_property fifo_depth DEFAULT_VALUE 10
set_parameter_property fifo_depth DISPLAY_NAME "Fifo depth"
set_parameter_property fifo_depth TYPE INTEGER
set_parameter_property fifo_depth UNITS None
set_parameter_property fifo_depth HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1



# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1



# 
# connection point avmms
# 
add_interface avmms avalon end
set_interface_property avmms addressUnits WORDS
set_interface_property avmms associatedClock clock
set_interface_property avmms associatedReset reset_n
set_interface_property avmms bitsPerSymbol 8
set_interface_property avmms burstOnBurstBoundariesOnly false
set_interface_property avmms burstcountUnits WORDS
set_interface_property avmms explicitAddressSpan 0
set_interface_property avmms holdTime 0
set_interface_property avmms linewrapBursts false
set_interface_property avmms maximumPendingReadTransactions 0
set_interface_property avmms maximumPendingWriteTransactions 0
set_interface_property avmms readLatency 0
set_interface_property avmms readWaitTime 1
set_interface_property avmms setupTime 0
set_interface_property avmms timingUnits Cycles
set_interface_property avmms writeWaitTime 0
set_interface_property avmms ENABLED true
set_interface_property avmms EXPORT_OF ""
set_interface_property avmms PORT_NAME_MAP ""
set_interface_property avmms CMSIS_SVD_VARIABLES ""
set_interface_property avmms SVD_ADDRESS_GROUP ""

add_interface_port avmms avmms_write_i write Input 1
add_interface_port avmms avmms_address_i address Input 3
add_interface_port avmms avmms_writedata_i writedata Input 32
add_interface_port avmms avmms_byteenable_i byteenable Input 4
add_interface_port avmms avmms_read_i read Input 1
add_interface_port avmms avmms_waitrequest_o waitrequest Output 1
add_interface_port avmms avmms_readdata_o readdata Output 32
set_interface_assignment avmms embeddedsw.configuration.isFlash 0
set_interface_assignment avmms embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avmms embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avmms embeddedsw.configuration.isPrintableDevice 0


# 
# connection point UART
# 
add_interface UART conduit end
set_interface_property UART associatedClock ""
set_interface_property UART associatedReset ""
set_interface_property UART ENABLED true
set_interface_property UART EXPORT_OF ""
set_interface_property UART PORT_NAME_MAP ""
set_interface_property UART CMSIS_SVD_VARIABLES ""
set_interface_property UART SVD_ADDRESS_GROUP ""

add_interface_port UART uart_rx uart_rx Input 1
add_interface_port UART uart_tx uart_tx Output 1



